package repository

import (
	"sort"

	"github.com/google/uuid"
	"hostettler.dev/dnc/models"
)

func TestCharacter(id uuid.UUID) CharacterAggregate {
	c := CharacterAggregate{
		Character: &models.CharacterTO{
			ID:                  id,
			Name:                "Bobby",
			ClassLevels:         "Wizard 10",
			Race:                "Gnome",
			Alignment:           "Chaotic Evil",
			ProficiencyBonus:    4,
			ArmorClass:          17,
			Initiative:          4,
			Speed:               30,
			MaxHitPoints:        100,
			CurrHitPoints:       50,
			TempHitPoints:       10,
			HitDice:             "10d6",
			UsedHitDice:         "5",
			DeathSaveSuccesses:  2,
			DeathSaveFailures:   2,
			Actions:             "Kick",
			BonusActions:        "Jump",
			SpellSlots:          []int{0, 5, 5, 5, 4, 3, 3, 3, 2, 1},
			SpellSlotsUsed:      []int{0, 3, 5, 4, 2, 2, 3, 1, 1, 0},
			SpellcastingAbility: "Cha",
			SpellSaveDC:         20,
			SpellAttackBonus:    10,
			Age:                 42,
			Height:              "4'11",
			Weight:              "200lbs",
			Eyes:                "Green",
			Skin:                "Pale",
			Hair:                "Brown",
			Appearance:          "Disheveled",
			Backstory:           "Noone",
			Personality:         "Crazy",
		},
		Abilities: &models.AbilitiesTO{
			CharacterID:  id,
			Strength:     10,
			Dexterity:    10,
			Constitution: 10,
			Intelligence: 10,
			Wisdom:       10,
			Charisma:     10,
		},
		SavingThrows: &models.SavingThrowsTO{
			CharacterID:             id,
			StrengthProficiency:     0,
			DexterityProficiency:    1,
			ConstitutionProficiency: 2,
			IntelligenceProficiency: 2,
			WisdomProficiency:       1,
			CharismaProficiency:     0,
		},
		Wallet: &models.WalletTO{
			CharacterID: id,
			Copper:      10,
			Silver:      20,
			Electrum:    30,
			Gold:        40,
			Platinum:    50,
		},
		Spells: []models.SpellTO{{
			ID:          uuid.New(),
			CharacterID: id,
			Name:        "Abracadabra",
			Level:       1,
			Prepared:    1,
			Damage:      "42d8",
			CastingTime: "Action",
			Range:       "600ft",
			Duration:    "Instant",
			Components:  "V/S/M",
			Description: "Boom",
		}},
		Items: []models.ItemTO{{
			ID:              uuid.New(),
			CharacterID:     id,
			Name:            "Stick",
			Equipped:        2,
			AttunementSlots: 3,
			Quantity:        1,
			Description:     "Stick",
		}},
		Attacks: []models.AttackTO{{
			ID:          uuid.New(),
			CharacterID: id,
			Name:        "Hit w/ Stick",
			Bonus:       15,
			Damage:      "10d6",
			DamageType:  "Necrotic",
		}},
		Skills: []models.CharacterSkillDetailTO{{
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        1,
			Proficiency:    1,
			CustomModifier: 0,
			SkillName:      "Athletics",
			SkillAbility:   "Strength",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        2,
			Proficiency:    0,
			CustomModifier: 0,
			SkillName:      "Acrobatics",
			SkillAbility:   "Dexterity",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        3,
			Proficiency:    2,
			CustomModifier: 0,
			SkillName:      "Sleight of Hand",
			SkillAbility:   "Dexterity",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        4,
			Proficiency:    1,
			CustomModifier: 0,
			SkillName:      "Stealth",
			SkillAbility:   "Dexterity",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        5,
			Proficiency:    0,
			CustomModifier: 0,
			SkillName:      "Arcana",
			SkillAbility:   "Intelligence",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        6,
			Proficiency:    0,
			CustomModifier: 0,
			SkillName:      "History",
			SkillAbility:   "Intelligence",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        7,
			Proficiency:    1,
			CustomModifier: 0,
			SkillName:      "Investigation",
			SkillAbility:   "Intelligence",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        8,
			Proficiency:    2,
			CustomModifier: 0,
			SkillName:      "Nature",
			SkillAbility:   "Intelligence",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        9,
			Proficiency:    1,
			CustomModifier: 0,
			SkillName:      "Religion",
			SkillAbility:   "Intelligence",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        10,
			Proficiency:    0,
			CustomModifier: 0,
			SkillName:      "Animal Handling",
			SkillAbility:   "Wisdom",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        11,
			Proficiency:    1,
			CustomModifier: 0,
			SkillName:      "Insight",
			SkillAbility:   "Wisdom",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        12,
			Proficiency:    0,
			CustomModifier: 0,
			SkillName:      "Medicine",
			SkillAbility:   "Wisdom",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        13,
			Proficiency:    0,
			CustomModifier: 0,
			SkillName:      "Perception",
			SkillAbility:   "Wisdom",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        14,
			Proficiency:    1,
			CustomModifier: 0,
			SkillName:      "Survival",
			SkillAbility:   "Wisdom",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        15,
			Proficiency:    2,
			CustomModifier: 0,
			SkillName:      "Deception",
			SkillAbility:   "Charisma",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        16,
			Proficiency:    2,
			CustomModifier: 0,
			SkillName:      "Intimidation",
			SkillAbility:   "Charisma",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        17,
			Proficiency:    0,
			CustomModifier: 0,
			SkillName:      "Performance",
			SkillAbility:   "Charisma",
		}, {
			ID:             uuid.New(),
			CharacterID:    id,
			SkillID:        18,
			Proficiency:    1,
			CustomModifier: 0,
			SkillName:      "Persuasion",
			SkillAbility:   "Charisma",
		}},
		Features: []models.FeatureTO{{
			ID:          uuid.New(),
			CharacterID: id,
			Name:        "Winged",
			Description: "Can fly",
		}},
		Notes: []models.NoteTO{
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Principia Mathematica",
				Note:        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Hidden Annotation #1",
				Note:        "Aliquam erat volutpat. Suspendisse potenti. Donec porta dui sed laoreet maximus; ante sapien facilisis risus, vitae sagittis odio nisl a justo. Integer facilisis ligula sed erat hendrerit, vitae aliquam metus viverra.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Arcane Memory #2",
				Note:        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non orci sed sapien tristique convallis. Integer facilisis ligula sed erat hendrerit, vitae aliquam metus viverra.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Fractured Note #3",
				Note:        "Phasellus non orci sed sapien tristique convallis. Accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis. Aliquam erat volutpat. Suspendisse potenti. Phasellus non orci sed sapien tristique convallis. Praesent consequat sapien quis elit pretium, sit amet dictum nisl cursus.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Ancient Theory #4",
				Note:        "Integer facilisis ligula sed erat hendrerit, vitae aliquam metus viverra. Aliquam erat volutpat. Suspendisse potenti. Donec porta dui sed laoreet maximus; ante sapien facilisis risus, vitae sagittis odio nisl a justo.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Ethereal Diary #5",
				Note:        "Accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis. Quisque vehicula tortor nec turpis laoreet, a feugiat risus gravida. Aliquam erat volutpat. Suspendisse potenti. Aliquam erat volutpat. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Fractured Fragment #6",
				Note:        "Integer facilisis ligula sed erat hendrerit, vitae aliquam metus viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Phasellus non orci sed sapien tristique convallis. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Starlit Scroll #7",
				Note:        "Praesent consequat sapien quis elit pretium, sit amet dictum nisl cursus. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Quisque vehicula tortor nec turpis laoreet, a feugiat risus gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Silent Note #8",
				Note:        "Accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis. Aliquam erat volutpat. Suspendisse potenti. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Lost Note #9",
				Note:        "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Aliquam erat volutpat. Suspendisse potenti. Praesent consequat sapien quis elit pretium, sit amet dictum nisl cursus.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Hidden Ritual #10",
				Note:        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Obscure Fragment #11",
				Note:        "Donec porta dui sed laoreet maximus; ante sapien facilisis risus, vitae sagittis odio nisl a justo. Phasellus non orci sed sapien tristique convallis. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Praesent consequat sapien quis elit pretium, sit amet dictum nisl cursus. Phasellus non orci sed sapien tristique convallis.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Ancient Diary #12",
				Note:        "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam. Accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Quisque vehicula tortor nec turpis laoreet, a feugiat risus gravida.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Starlit Record #13",
				Note:        "Quisque vehicula tortor nec turpis laoreet, a feugiat risus gravida. Praesent consequat sapien quis elit pretium, sit amet dictum nisl cursus. Donec porta dui sed laoreet maximus; ante sapien facilisis risus, vitae sagittis odio nisl a justo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Integer facilisis ligula sed erat hendrerit, vitae aliquam metus viverra.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Silent Treatise #14",
				Note:        "Praesent consequat sapien quis elit pretium, sit amet dictum nisl cursus. Quisque vehicula tortor nec turpis laoreet, a feugiat risus gravida. Phasellus non orci sed sapien tristique convallis.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Lost Theory #15",
				Note:        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Fractured Codex #16",
				Note:        "Aliquam erat volutpat. Suspendisse potenti. Quisque vehicula tortor nec turpis laoreet, a feugiat risus gravida. Praesent consequat sapien quis elit pretium, sit amet dictum nisl cursus. Praesent consequat sapien quis elit pretium, sit amet dictum nisl cursus.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Fractured Note #17",
				Note:        "Aliquam erat volutpat. Suspendisse potenti. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non orci sed sapien tristique convallis. Quisque vehicula tortor nec turpis laoreet, a feugiat risus gravida.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Forgotten Codex #18",
				Note:        "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Crimson Memory #19",
				Note:        "Donec porta dui sed laoreet maximus; ante sapien facilisis risus, vitae sagittis odio nisl a justo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Phasellus non orci sed sapien tristique convallis.",
			},
			{
				ID:          uuid.New(),
				CharacterID: id,
				Title:       "Hidden Memory #20",
				Note:        "Phasellus non orci sed sapien tristique convallis. Integer facilisis ligula sed erat hendrerit, vitae aliquam metus viverra. Phasellus non orci sed sapien tristique convallis.",
			},
		},
	}
	// Ensure deterministic alphabetical order by Title so persistence test matches
	sort.Slice(c.Notes, func(i, j int) bool { return c.Notes[i].Title < c.Notes[j].Title })
	return c
}
